### ISSUE TITLE
Contenuti direttamente nel main

### ISSUE THREAD

**Issue by Polpetta** [BugBusterSWE/documentation#10]
Ciao,
gli assegnatari del PianoDiProgetto hanno scritto i contenuti direttamente nel main, e questo non va bene!
I contenuti devono essere messi in un file a parte dentro `res/chapters/` (in caso la cartella non sia presente createla) e aggiunti al file `res/listOfChapters.tex`.
Da fixare

**Comment by korut94** [comment]
Ho fatto, chiudo.
