### ISSUE TITLE
Aggiungere struttura del repository

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#103]
_Documento in cui si trova il problema_:
Norme di Progetto

_Descrizione del problema_:
Manca la definizione della struttura del repository

_Punti da svolgere per risolvere il problema_:
- [ ] Aggiungere una sottosezione riguardante la nuova gestione del repository

Link task: [https://bugbusters.teamwork.com/tasks/5864650](https://bugbusters.teamwork.com/tasks/5864650)

**Comment by Polpetta** [comment]
@mdipirro quando posso cominciare a fare questo task?
