### ISSUE TITLE
Progettazione classi Editor

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#104]
_Documento in cui si trova il problema_:
Specifica Tecnica

_Descrizione del problema_:
Manca la progettazione dell'editor

_Punti da svolgere per risolvere il problema_:
- [ ] Progettare le classi dell'editor

Link task: [https://bugbusters.teamwork.com/tasks/5876472](https://bugbusters.teamwork.com/tasks/5876472)

**Comment by korut94** [comment]
Chiusura issue con commit [939a782](https://github.com/BugBusterSWE/documentation/commit/939a78291bd8539e7058f73d5f40393f209d15d6).
