### ISSUE TITLE
Riunione 21/03/16

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#108]
Definire ordine del giorno per la riunione del 21/03/16

Link task: [https://bugbusters.teamwork.com/tasks/5881104](https://bugbusters.teamwork.com/tasks/5881104)

**Comment by mdipirro** [comment]
- dimostrazione glossario xml

**Comment by Polpetta** [comment]
Mettilo come commento su Teamwork insieme agli altri!! :)
Il 19 mar 2016 11:59, "Matteo Di Pirro" notifications@github.com ha
scritto:

**Comment by mdipirro** [comment]
ups vero =)
