### ISSUE TITLE
Sistemare Tracy

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#127]
Studiare e sistemare la struttura di Tracy

Link task: [https://bugbusters.teamwork.com/tasks/5937442](https://bugbusters.teamwork.com/tasks/5937442)

**Comment by drigoni** [comment]
Una serie di punti per tenere traccia di ciò che è stato fatto:
- [x] Togliere cose aggiuntive (Giochi, robe c++ ed ecc...)
- [x] Sistemare i bug della home
- [x] Aggiungere account dei membri di BugBusters
- [x] Show Glossary
- [x] Aggiungere la ricerca a Glossary
- [x] Permettere la rimozione a Glossary
- [x] Permettere la creazione a Glossary
- [x] Permettere la modifica a Glossary
- [x] Permettere l'esportazione in XML del Glossary - non urgente
- [x] Aggiungere tutte le voci già presenti nel Glossario
- [ ] aggiungere tutti i requisiti
- [ ] aggiungere tutti i test

**Comment by drigoni** [comment]
Appena @mdipirro da il via potete adoperare Tracy per aggiungere le voci del glossario

**Comment by Polpetta** [comment]
@drigoni chiudo in quanto non serve piu'.
