### ISSUE TITLE
Lingua del glossario

### ISSUE THREAD

**Issue by Polpetta** [BugBusterSWE/documentation#17]
Ciao!
@BugBusterSWE/customers Il glossario (che potete vedere nel branch `test/Glossario`) lo desiderate avere in inglese o vi va bene anche in italiano? :blush:

**Comment by alemhnan** [comment]
Italiano va benissimo

**Comment by alemhnan** [comment]
(chiuso per sbaglio, pardon)

**Comment by mdipirro** [comment]
Italiano

## 

Matteo Di Pirro
Il 13/gen/2016 16:35, "Alessandro Maccagnan" notifications@github.com ha
scritto:

**Comment by Polpetta** [comment]
@BugBusterSWE/customers ok!!
