### ISSUE TITLE
Sistemare lista modifiche - PdQ

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#180]
_Documento in cui si trova il problema_: 
Piano di Qualifica

_Descrizione del problema_: 
Aggiungere le modifiche del documento

_Punti da svolgere per risolvere il problema_: 
- [x] Sistemare lista modifiche

Link task: [https://bugbusters.teamwork.com/tasks/6162085](https://bugbusters.teamwork.com/tasks/6162085)

**Comment by drigoni** [comment]
§2: apprezzabile il tentativo di correlare la presentazione degli obiettivi di
qualità con metriche a essi associate; l'esito tuttavia è insoddisfacente perché
vi è troppa distanza e sparsità tra il punto in cui gli obiettivi sono enunciate e
quello in cui essi vengono quantificati in relazione a specifiche metriche.
§3.1: da rivedere la definizione di "error". §B.1.1: da rivedere l'interpretazione
del ciclo di Deming. Nel complesso, documento con buone intenzioni, ma
contenuti insufficienti per ampiezza e profondità.
