### ISSUE TITLE
Sistemare lista modifiche - PdP

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#184]
_Documento in cui si trova il problema_: 
Piano Di Progetto
_Descrizione del problema_: 
Aggiungere le modifiche del documento

_Punti da svolgere per risolvere il problema_: 
- [x] Sistemare lista modifiche

Link task: [https://bugbusters.teamwork.com/tasks/6162115](https://bugbusters.teamwork.com/tasks/6162115)

**Comment by drigoni** [comment]
- [x] Analisi
- [x] Analisi Miglioramenti
- [x] Progettazione Architetturale
