### ISSUE TITLE
Sistemare lista modifiche - NdP

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#185]
_Documento in cui si trova il problema_: 
Norme di Progetto

_Descrizione del problema_: 
Aggiungere le modifiche del documento

_Punti da svolgere per risolvere il problema_: 
- [ ] Sistemare lista modifiche

Link task: [https://bugbusters.teamwork.com/tasks/6162561](https://bugbusters.teamwork.com/tasks/6162561)

**Comment by drigoni** [comment]
- [x] Analisi
- [x] Analisi Miglioramenti
- [x] Progettazione Architetturale
