### ISSUE TITLE
Aggiunta funzionalita' a UCManager.sh

### ISSUE THREAD

**Issue by korut94** [BugBusterSWE/documentation#19]
Dopo aver inserito l'aggiunta delle inclusioni lo script segnala errore. Da risolvere.

**Comment by Polpetta** [comment]
@korut94 prova a vedere se ora va. Nota che c'e' ancora `\subsection [...]` e non `\subsubsection [...]`. Penso che tu abbia creato il branch senza pullare le modifiche prima. In ogni caso, prova a vedere se ora funziona. Se funziona mergia prestando attenzione che in `test/AnalisiDeiRequisiti` rimanga `\subsubsection`, altrimenti tutta l'identazione poi viene errata.

**Comment by korut94** [comment]
Ho finito, chiudo.
