### ISSUE TITLE
Aggiornare documenti a nuovo layout

### ISSUE THREAD

**Issue by Polpetta** [BugBusterSWE/documentation#20]
Ogni documento deve adattarsi al nuovo layout adottato.
Documenti da adattare:
- [x] Norme di Progetto
- [x] Analisi dei Requisiti
- [x] Glossario
- [x] Piano di Qualifica
- [x] Piano di Progetto

**Comment by Cyofanni** [comment]
perdonami ma non capisco cosa significa, ad esempio nel mio capitolo delle Norme devo cambiare qualcosa?

**Comment by Polpetta** [comment]
@Cyofanni no, il contenuto rimarrà inalterato. Se vuoi vedere le modifiche, apri un documento tra quelli già portati al nuovo layout (ovvero quelli depennati dalla lista) e prova a dare:

``` sh
latexmk -pdf
```

E dovresti vedere le nuove modifiche.

**Comment by Cyofanni** [comment]
capito

**Comment by Polpetta** [comment]
@Cyofanni a te come sembra il layout?

**Comment by Cyofanni** [comment]
@Polpetta dove devo dare il comando latexmk -pdf, in che directory?

**Comment by Polpetta** [comment]
Nella directory dove si trova il file main.tex!
Il 14 gen 2016 14:47, "Giovanni Mazzocchin" notifications@github.com ha
scritto:
