### ISSUE TITLE
Cambiare data documento e aggiungere redattori/verficatori/uso

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#207]
_Documento in cui si trova il problema_: 
Specifica Tecnica 

_Descrizione del problema_: 
Mancano alcune informazioni

_Punti da svolgere per risolvere il problema_: 
- [x] -Cambiare data
- [x] Aggiungere informazioni stesura

Link task: [https://bugbusters.teamwork.com/tasks/6209593](https://bugbusters.teamwork.com/tasks/6209593)

**Comment by mdipirro** [comment]
Fatto in issue#87
