### ISSUE TITLE
Aggiungere misurazioni Gulpease, SV, BV

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#211]
_Documento in cui si trova il problema_: 
Piano di Qualifica

_Descrizione del problema_: 
Mancano le misurazioni del gulpease dei documenti e le misure di schedule variance e budget variance

_Punti da svolgere per risolvere il problema_: 
- [x] Inserire gulpease
- [x] Inserire SV per AR, AM, PA
- [x] Inserire BV per AR, AM, PA

Link task: [https://bugbusters.teamwork.com/tasks/6209601](https://bugbusters.teamwork.com/tasks/6209601)

**Comment by korut94** [comment]
@mdipirro gli indici li calcolo nella versione presente nel master? SV e BV non gli ho mai calcolati, ho visto nelle norme di progetto ma non è molto chiaro. Mi spiegheresti come devo fare?

**Comment by korut94** [comment]
Queste sono le misurazioni dei Gulpease nel periodo **Analisi Miglioramenti**:

| Documento | Valore |
| --- | :-: |
| Analasi dei requisiti | 61 |
| Norme di progetto | 47 |
| Studio di fattibilita | 57 |
| Piano di progetto | 57 |
| Piano di qualifica | 64 |

**Comment by mdipirro** [comment]
Le misurazioni di SV e BV, per i tre periodi che abbiamo attraversato (quindi compresa anche l'analisi, per la quale non erano state fatte) sono:

| Periodo | Indice | Valore |
| --- | --- | :-: |
| Analisi | SV | 0 |
| Analisi | BV | -106,00 |
| Analisi Miglioramenti | SV | -1 |
| Analisi Miglioramenti | BV | -7,00 |
| Progettazione Architetturale | SV | 0 |
| Progettazione Architetturale | BV | -23,00 |

L'unità di misura di SV sono le ore, di BV sono euro. un valore negativo significa che c'è stato un risparmio. Lo 0 in SV e un risparmio in BV è coerente con il fatto che sono state fatte più ore per alcuni ruoli e meno per altri, quindi il costo finale ne risente. 
Ti sarei grato se potessi inserire anche queste misure quando riporti il gulpease.

**Comment by korut94** [comment]
In quale file metto questa tabella?

**Comment by mdipirro** [comment]
Dovresti dividerla per periodi, come abbiamo fatto per il gulpease.. comunque in appendice insieme al gulpease

**Comment by korut94** [comment]
Ho capito dove metterla, ma sta cosa dei periodi mi sfugge come rappresentarla.

**Comment by korut94** [comment]
Chiudo la issue in quanto svolti tutti i punti,
