### ISSUE TITLE
Formattazione tabella di descrizione dei casi d'uso

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#25]
Nella tabella di descrizione di un caso d'uso, nella voce "Scopo e Descrizione" il "ne" di "Descrizione" va a capo, creando un brutto effetto. 
![bug](https://cloud.githubusercontent.com/assets/15051389/12371690/5f979f84-bc3c-11e5-8d74-169f6cda6b7e.png)

**Comment by Polpetta** [comment]
A quelli di Steakholders veniva questo effetto?

**Comment by mdipirro** [comment]
No

**Comment by Polpetta** [comment]
Ok, allora adesso controllo cosa c'è che non va. Al massimo sarebbe un
problema accorciare "Descrizione" con una abbreviazione o addirittura
rimuoverlo?
Il 17 gen 2016 09:57, "Matteo Di Pirro" notifications@github.com ha
scritto:

**Comment by mdipirro** [comment]
Mmmh.. piuttosto che toglierlo o accorciarlo lascia che vada a capo

**Comment by Polpetta** [comment]
Ok. In ogni caso ora ci do un'occhiata. Perchè quenado ho preso il loro layout ho lasciato stare alcune loro modifiche alla geometria delle pagine (perchè non volevo prendere senza capirci nulla), penso che sia uno di quelle cose non importate il problema.

**Comment by Polpetta** [comment]
@mdipirro Lascio questa issue aperta per la fase successiva.

**Comment by mdipirro** [comment]
Ottimo

**Comment by mdipirro** [comment]
guardando il pdf ora sembra essersi risolto

**Comment by Polpetta** [comment]
@mdipirro Ho notato anche io, pur non avendo fatto nulla. Mah! Mistero

**Comment by mdipirro** [comment]
chiudo??

**Comment by Polpetta** [comment]
@mdipirro si chiudila, che se si ripresenta la riapriamo!! :blush:
