### ISSUE TITLE
Chi trascrive il glossario nella fase AN del PdP

### ISSUE THREAD

**Issue by korut94** [BugBusterSWE/documentation#26]
Commentati gli orari su chi dirige il lavoro. Da deciderlo con il gruppo.

**Comment by Polpetta** [comment]
@korut94 E' stato deciso?

**Comment by korut94** [comment]
No. Almeno mi risulta cosi.

**Comment by Polpetta** [comment]
@korut94 Chi dovrebbe occuparsene?

**Comment by Polpetta** [comment]
@korut94 A che punto e' questa issue?

**Comment by korut94** [comment]
Minima idea.

**Comment by Polpetta** [comment]
Grey ottimo direi

**Comment by mdipirro** [comment]
Lascio aperta per eventuali correzioni post RR

**Comment by Polpetta** [comment]
@mdipirro Ok

**Comment by korut94** [comment]
Chiudo, ormai è passato.

**Comment by Polpetta** [comment]
Di verdure?
