### ISSUE TITLE
Lettera di presentazione non compila

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#27]
La lettera di presentazione non compila, e non vorrei fare casini toccando i file comuni

**Comment by Polpetta** [comment]
Ok, puoi postarmi cosa ti dice il compilatore?
Il 17 gen 2016 11:16 AM, "Matteo Di Pirro" notifications@github.com ha
scritto:

**Comment by mdipirro** [comment]
![schermata del 2016-01-17 12 01 27](https://cloud.githubusercontent.com/assets/15051389/12377121/204e9f22-bd12-11e5-881c-56636a4da9f4.png)
Ti mando la schermata compilata da qui così si capisce meglio. Comunque in effetti genera il pdf, ma non lo fa formato lettera.
Se cambio la documentclass sullo stile in letter invece dice questo:
![schermata del 2016-01-17 12 04 04](https://cloud.githubusercontent.com/assets/15051389/12377129/6c3a8266-bd12-11e5-84a7-ce5e6714e922.png)

Nel primo caso genera questo:
![schermata del 2016-01-17 12 06 18](https://cloud.githubusercontent.com/assets/15051389/12377141/beabb808-bd12-11e5-8694-688465cbb8ae.png)

Nel secondo caso genera questo:
![schermata del 2016-01-17 12 05 22](https://cloud.githubusercontent.com/assets/15051389/12377138/a3c123a2-bd12-11e5-8a1a-f87027536879.png)

**Comment by Polpetta** [comment]
Ok, allora te nel main.tex hai il seguente codice:

``` tex
\input{../../common/style/global.tex}
\input{../../common/style/layout.tex}

\begin{document}
\include{res/letter}
\end{document}
```

Prova a sostituirlo con

``` tex
\input{../../common/style/global.tex}
\input{../../common/style/layout.tex}

\begin{letter}
\include{res/letter}
\end{letter}
```

Nel file letter.tex rimuovi la riga 2 e la 38. 

Se dovesse darti ancora problemi sempre nel file letter.tex sposta la riga 1 e ponila nel file main.tex prima del `\begin{letter}`.

Ora va?

**Comment by mdipirro** [comment]
No, così mi dice:
![schermata del 2016-01-17 12 25 36](https://cloud.githubusercontent.com/assets/15051389/12377208/6e73ebc8-bd15-11e5-9e46-16ce925d7776.png)

e non genera il pdf.

**Comment by Polpetta** [comment]
@mdipirro Ora ho fixato tutto e da me funziona. Ti ricordo (come deciso) che i documenti si dovrebbero compilare eseguendo il comando `latexmk -pdf` sulla directory dove si trova il file `main.tex`.  Altri comandi potrebbero funzionare, ma non so assicurartelo.

In ogni caso sappimi dare un responso se funziona. Se va chiudi la issue! :blush: 

P.S.: per fixare la build ho seguito la ![seguente documentazione](https://en.wikibooks.org/wiki/LaTeX/Letters) :blush:

**Comment by mdipirro** [comment]
Lo so per la compilazione, ho mostrato l'altro perché erano tutti vicini e si capivano meglio. Ora va perfettamente. Chiudo

**Comment by Polpetta** [comment]
Sisi non ci sono problemi!! Dico solo che quando andremo a consegnare
generiamo i PDF col comando che di ho dato, perché è più semplice farci uno
script sopra per generarli!:D e anche per travis!:)
Il 17 gen 2016 15:08, "Matteo Di Pirro" notifications@github.com ha
scritto:
