### ISSUE TITLE
Sistemare accenti

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#276]
_Documento in cui si trova il problema_:
Activity #269 
Tutti

_Descrizione del problema_:
Accentazioni sbagliate nei vari documenti. Da controllare

Link task: [https://bugbusters.teamwork.com/tasks/6455674](https://bugbusters.teamwork.com/tasks/6455674)

**Comment by korut94** [comment]
@mdipirro oltre a sistemare gli accenti devo sostituire il comando LaTeX con il rispettivo carattere UTF-8?

**Comment by mdipirro** [comment]
se riesci secondo me sarebbe meglio, ma l'importante è che gli accenti siano corretti. Puoi lavorare su Norme, Analisi, PdP e PdQ, la ST è ancora in lavorazione ed è meglio evitare possibili conflitti
