### ISSUE TITLE
Analisi dei Requisiti (per i Verificatori)

### ISSUE THREAD

**Issue by EmanueleC** [BugBusterSWE/documentation#28]
Ai verificatori: ho individuato i seguenti punti da rivedere/correggere, o da discutere insieme a chi ha scritto l'Analisi dei Requisiti:
- Mancano flusso principale, estensioni ed inclusioni in alcuni casi d'uso dell'editor.
- Controllare che le parole Cell, Document, Collection e Dashboard appaiano sempre con la prima lettera maiuscola.
- Controllare le etichette dei diagrammi nelle immagini.
- Nei casi d'uso che riguardano l'inserimento di una password vanno imposti dei vincoli? (ad esempio una lunghezza di 8 caratteri) Se decidiamo di aggiungerli vanno inserite delle inclusioni per effettuare il controllo.
- Vanno inserite delle inclusioni per effettuare dei controlli nel db di MaaS nei casi d'uso che richiedono in combinazione l'inserimento di email/password (ad esempio il login)?
- UC-U12, UC-U13.6.2 hanno dei nomi troppo lunghi. Come cambiarli?
- UC-U15 e casi d'uso innestati: occorre specificare che trattano di funzionalità offerte dall'interfaccia delle varie pagine e non dall'editor?
- Da controllare UC-U16.5.3
- Nei casi d'uso dell'editor che riguardano l'editor non si menzionano i nuovi tipi di dato che MaaS accetta. 
- Sostituire "flusso principale" con "scenario principale"?

Sono stati inseriti tutti i casi d'uso dell'utente.

Altre info generali:
- Alcuni sotto casi d'uso non sono stati inseriti in tabella poiché non aggiungono funzionalità rispetto ai loro genitori (ad esempio UC-U3.1)

Poiché ho scritto una parte di questo documento di sicuro mi è sfuggito qualcosa nel ricontrollarlo. Quindi la lista sopra non vi permette di fare Inspection... purtroppo.

**Comment by EmanueleC** [comment]
@drigoni e @WeissL

**Comment by drigoni** [comment]
Fatti: UC-U14, UC-U9.3, UC-U9.4, UC-U13.1, UC-U13.2, UC-U13.3
Rimanenti: UC-U15.2, UC-U16.7.1 ... 16.7.7, UC-U17
Problema riscontrato: 
1. Nella immagine  UC-U15 il casod ella rimozione è  UC-U15.5 e non  UC-U15.2

**Comment by drigoni** [comment]
Fatti: UC-U14, UC-U9.3, UC-U9.4, UC-U13.1, UC-U13.2, UC-U13.3, UC-U17
Rimanenti: UC-U15.2, UC-U16.7.1 ... 16.7.7
Problema riscontrato:
Problema risolto:
1. Vedi sopra

**Comment by drigoni** [comment]
Fatti: UC-U14, UC-U9.3, UC-U9.4, UC-U13.1, UC-U13.2, UC-U13.3, UC-U15.2, UC-U17
Rimanenti: UC-U16.7.1 ... 16.7.7

**Comment by Polpetta** [comment]
@drigoni aggiorna il campo "estimate" sulla issue per mettere quanto tempo e' necessario, in modo tale che venga nel grafico utile per @mdipirro, grazie :blush:

**Comment by EmanueleC** [comment]
Sono stati aggiunti gli ultimi casi d'uso dell'utente.

**Comment by Polpetta** [comment]
@EmanueleC da quel che ho capito questa issue e' completa, quindi la chiudo issue. Se ci sono altre cosa mancanti riaprila.
