### ISSUE TITLE
Aggiungere Glossario a make

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#282]
_Documento in cui si trova il problema_: 
Activity #269
Glossario

_Descrizione del problema_: 
Sistemare makefile con compilazione glossario

Link task: [https://bugbusters.teamwork.com/tasks/6456543](https://bugbusters.teamwork.com/tasks/6456543)

**Comment by Polpetta** [comment]
- [x] cambiare fase da RP a RQ
- [x] nell'if del glossario verificare se è una vecchia versione o se si sta utilizzando un xml. Si potrebbe controllare l'esistenza del .xml e in quel caso eseguire lo script di matteo

**Comment by Polpetta** [comment]
> nell'if del glossario verificare se è una vecchia versione o se si sta utilizzando un xml. Si potrebbe controllare l'esistenza del .xml e in quel caso eseguire lo script di matteo

Stronzata in quanto non è necessario -> entrambi i CI eseguono il make, quindi è lecito che ci siano make differenti, comunque saranno consistenti con le modifiche fatte nel glossario! 
- [x] Bisogna aggiungeer nei sistemi di CI le dipendenze perl

Memo: PR di questa su branch di @mdipirro #283
