### ISSUE TITLE
Aggiungere nomra del corsivo per parole inglesi

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#291]
_Documento in cui si trova il problema_: 
Activity #285
Norme di Progetto

_Descrizione del problema_: 
Inserire norme per le parole inglesi

Link task: [https://bugbusters.teamwork.com/tasks/6456695](https://bugbusters.teamwork.com/tasks/6456695)

**Comment by Cyofanni** [comment]
fatto io per sbaglio, chiudo

**Comment by Polpetta** [comment]
Un bello sbaglio :D
Il 27 apr 2016 15:32, "Giovanni Mazzocchin" notifications@github.com ha
scritto:
