### ISSUE TITLE
Aggiungere assegnazione automatica verificatori

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#294]
_Documento in cui si trova il problema_: 
Activity #285
Norme di Progetto

_Descrizione del problema_: 
Inserire descrizione dell'assegnazione automatica

Link task: [https://bugbusters.teamwork.com/tasks/6456721](https://bugbusters.teamwork.com/tasks/6456721)

**Comment by korut94** [comment]
@mdipirro la sezione sull'assegnazione automatica la metto nei processi di supporto o organizzativi?

**Comment by korut94** [comment]
Ok trovato! Nessun problema.
