### ISSUE TITLE
Tipo di documenti

### ISSUE THREAD

**Issue by Polpetta** [BugBusterSWE/documentation#3]
Ciao a tutti,
chiedo qui una vostra considerazione. Per il momento noi stiamo lavorando in documenti latex che hanno forma di _libro_:

``` tex
\documentclass[11pt,a4paper]{book}
```

Mi sto chiedendo se è da tenere questo è il formato giusto o se è meglio usare `article`.
Che ne pensate?

**Comment by EmanueleC** [comment]
[Qui](https://en.wikibooks.org/wiki/LaTeX/Document_Structure#Document_classes)  scrivono:

article:    for articles in scientific journals, presentations, short reports, program documentation, 
report: for longer reports containing several chapters, small books, thesis, ...
book:   for real books.

Secondo me la scelta è fra report e article.

**Comment by mdipirro** [comment]
Se dobbiamo tenere una struttura fissa per tutti i documenti -> article
Se possiamo cambiare struttura -> article per la documentazione tecnica e report per norme

**Comment by Polpetta** [comment]
Ok, quindi aggiorniamo tutti i documenti con article?
Io direi di farlo adesso che abbiamo scritto relativamente poco latex, che altrimenti dopo diventerà un inferno! :smile:

**Comment by Polpetta** [comment]
Bon, chiudo questa e apro una issue per ricordami di "traslare" tutti i tipi di documenti da `book` a `article`.
