### ISSUE TITLE
Norme di Progetto - verifica

### ISSUE THREAD

**Issue by EmanueleC** [BugBusterSWE/documentation#31]
Nel file listOfSections.tex non sono incluse l'introduzione e la parte dei processi di supporto.

**Comment by EmanueleC** [comment]
@WeissL e @Cyofanni manca un paragrafo dove viene descritto il codice identificativo per i requisiti della AR. Lo inserisco io dopo aver scritto i requisiti, ok?

**Comment by Cyofanni** [comment]
ok

**Comment by Polpetta** [comment]
@EmanueleC il problema e' risolto? La issue si puo' chiudere?

**Comment by Cyofanni** [comment]
chiudo io
