### ISSUE TITLE
UC-S4 non ha un nome parlante

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#316]
Documento in cui si trova il problema: 
Activity #302 
Analisi dei Requisiti 

Descrizione del problema: 
Dare un nome parlante a UC-S4

Link task: [https://bugbusters.teamwork.com/tasks/6461147](https://bugbusters.teamwork.com/tasks/6461147)

**Comment by mdipirro** [comment]
Anzi guardando meglio sembra duplicato e prima di UC-S3
