### ISSUE TITLE
Per utenteNA.tex, aggiungere il caso d'uso UC-2

### ISSUE THREAD

**Issue by Cyofanni** [BugBusterSWE/documentation#33]
Aggiungere anche UC-5 nello stesso file,@EmanueleC e @drigoni , anche UCU-6 e UCU-7 da rivedere nello stesso file

**Comment by Cyofanni** [comment]
@EmanueleC e @drigoni

**Comment by Polpetta** [comment]
@Cyofanni puoi taggare interi team di persone per far prima. Puoi trovare i nomi dei tag qui: https://github.com/orgs/BugBusterSWE/teams.
Per esempio per taggare il team che si occupava dei casi d'uso editor puoi usare:
@BugBusterSWE/adr-user
