### ISSUE TITLE
Analizzare meglio consuntivo sezione 6

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#330]
Documento in cui si trova il problema: 
Activity #327
Piano di Progetto

Descrizione del problema: 
Analizzare il consuntivo in sezione 6 e renderlo più chiaro ed approfondito, secondo quanto scritto nella correzione

Link task: [https://bugbusters.teamwork.com/tasks/6461224](https://bugbusters.teamwork.com/tasks/6461224)

**Comment by drigoni** [comment]
Risposta di Tullio al riguardo:

> Il commento serve per farvi osservare che, dai consuntivi, si impara di più guardando prima ai numeri globali e poi scendendo nel dettaglio sulla possibile origine delle discrepanze. Voi invece guardate solo al dettaglio di ogni periodo e non vi interrogate sulla visione d'insieme.
> Quanto alla collocazione, il consuntivo va certamente tenuto a parte dal preventivo iniziale, mentre è premessa necessaria all'aggiornamento del preventivo per il periodo rimanente (ciò che, sapete, si chiama, preventivo a finire).
