### ISSUE TITLE
Sistemare PAF

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#331]
Documento in cui si trova il problema: 
Activity #327
Piano di Progetto

Descrizione del problema: 
Sistemare PAF secondo quanto scritto nella correzione

Link task: [https://bugbusters.teamwork.com/tasks/6461225](https://bugbusters.teamwork.com/tasks/6461225)

**Comment by drigoni** [comment]
Risposta di Tullio al riguardo:

> Il commento serve per farvi osservare che, dai consuntivi, si impara di più guardando prima ai numeri globali e poi scendendo nel dettaglio sulla possibile origine delle discrepanze. Voi invece guardate solo al dettaglio di ogni periodo e non vi interrogate sulla visione d'insieme.
> Quanto alla collocazione, il consuntivo va certamente tenuto a parte dal preventivo iniziale, mentre è premessa necessaria all'aggiornamento del preventivo per il periodo rimanente (ciò che, sapete, si chiama, preventivo a finire).

**Comment by mdipirro** [comment]
@drigoni come sei messo qui?

**Comment by drigoni** [comment]
Sto cercando di capire come impostargli il documento
