### ISSUE TITLE
Sistemare caso d'uso 11

### ISSUE THREAD

**Issue by WeissL** [BugBusterSWE/documentation#35]
@drigoni

**Comment by WeissL** [comment]
Lista dei problemi:
- UC-11.1 Non è chiaro come l'utente può eseguire una specifica DSL, bisognerebbe riportare almeno come fa ad eseguirla nello "scenario principale"
- UC-11.1 Estensione -> se non ha i permessi per visualizzarla allora non la deve vedere!
  -UC11.2 la modifica di una dsl avviene attraverso l'editor... bisogna segnalarne almeno il collegamento
  -UC11.3 la creazione di una DSL richiama i casi d'uso dell'editor. Bisogna linkare le due cose. Per l'estensione stessi problemi delle due precedenti: se non ha i permessi per metterci le mani non può arrivare qui!
  -UC11.4 Gli utenti trovano la lista delle DSL in dashboard? Qualche caso d'uso più in la in dashboard sono definiti gli elementi dei contenuto... quale versione è più giusta?

**Comment by WeissL** [comment]
UC 12 si collega al punto 2 della issue

**Comment by WeissL** [comment]
UC14 collegato al punto 2

**Comment by drigoni** [comment]
UC-U11.1 -> Non ho ben chiaro come dovrebbe fare e dunque lo chiedo a voi...
UC11.4 -> Non possono esserci entrambe?
Per gli altri punti che faccio?
