### ISSUE TITLE
Dubbio sul concetto di ordinamento su Cell

### ISSUE THREAD

**Issue by Cyofanni** [BugBusterSWE/documentation#36]
@alemhnan, @daschy 
puoi darci una spiegazione piu' precisa su questa affermazione del capitolato?: 
"A cell can take as input the result of a query in the specified mongo collection. The results
can be ordered by a specific attribute field. The value visualized is the the first value of the
results set."

**Comment by alemhnan** [comment]
L'idea di una cella e' di poter visualizzare valori arbitrari. L'origine di questi valori puo' essere molteplice, una chiamata API, un calcolo lato server, o un valore specifico nel database. 

Il testo nel capitolato fa riferimento a una sola di queste modalita': una proiezione di una collection nel database. Non sono richiesti altre modalita' (chiamata API,calcolo lato server o altro), ma sono veramente interessanti da considerare per molteplici motivi che non descrivo qui (in caso chiedete se interessati). 

Se per esempio voglio visualizzare quanti utenti totali ci sono posso fare una chiamata 'count' al database e visualizzare direttamente il valore restituito, garantito essere singolo. 

Se invece di usare una chiamata che garantisce di usare un valore solo (e.g. 'count') uso una chiamata che ritorna un insieme di valori ('result set') (e.g. 'find') devo sapere quale valore visualizzare nella cella. Arbitrariamente diciamo che e' il primo valore del risultato. Per avere un minimo di controllo diamo la possibilita' di ordinare specificando un attributo di ordinamento.

**Comment by Cyofanni** [comment]
grazie per delucidazione
