### ISSUE TITLE
Aggiungere descrizione delle relazioni moduli Editor

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#368]
Documento in cui si trova il problema: 
Activity #318
Specifica Tecnica

Descrizione del problema: 
Descrivere le relazioni tra i moduli dell'editor come chiesto nella correzione

Link task: [https://bugbusters.teamwork.com/tasks/6486664](https://bugbusters.teamwork.com/tasks/6486664)

**Comment by korut94** [comment]
@EmanueleC questa issue si può chiudere?
