### ISSUE TITLE
Aggiungere descrizione delle relazioni moduli Interprete

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#369]
Documento in cui si trova il problema: 
Activity #318 
Specifica Tecnica 

Descrizione del problema: 
Descrivere le relazioni tra i moduli dell'interprete come chiesto nella correzione

Link task: [https://bugbusters.teamwork.com/tasks/6486802](https://bugbusters.teamwork.com/tasks/6486802)

**Comment by korut94** [comment]
@mdipirro non mi e' proprio chiaro cosa devo descrivre.
Le relazione tra le componenti dentro il package DSLInterpreter o le relazioni con chi usa il package?

**Comment by mdipirro** [comment]
Se nel documento parli di entrambe allora descrivi entrambe

**Comment by korut94** [comment]
Ok, quindi mi limito alla sezione sull'interprete.
