### ISSUE TITLE
Rivedere pesantemente casi d'uso in editor.tex

### ISSUE THREAD

**Issue by Cyofanni** [BugBusterSWE/documentation#37]
@BugBusterSWE/adr-editor 
1) Numerazione dei casi d'uso
2) Assenza di UC-E1
3) Gli elenchi numerici devono andare a capo
4) In alcuni la precondizione e' uguale allo scopo, non va bene

**Comment by korut94** [comment]
Qual'è il problema della numerazione? Dove hai trovato precondizioni uguali allo scopo?

**Comment by Cyofanni** [comment]
la numerazione non e' conforme a quella utilizzata dagli altri, riferirsi ai casi d'uso degli utenti
non autenticati;
inoltre ci sono copia e incolla tra scopo e precondizione, guarda attentamente

**Comment by korut94** [comment]
Ma da quando la numerazione deve essere incrementale anche sugli altri casi?

**Comment by Cyofanni** [comment]
devono partire da 0 come gli altri, e non c'e' l'1

**Comment by korut94** [comment]
Non capisco Cyofanni, intendi che non seguiamo l'incremento o inseriamo anche i casi d'uso numerati con tre punti?

**Comment by korut94** [comment]
Ok ho capito. Adesso vediamo di sistemare.

**Comment by Polpetta** [comment]
1) Cosa c'è che non va?
2) @korut94 risolvi te
3) Questo non è possibile per come è stato scritto LaTeX, se vedi anche gli
steakholders presentano questo difetto. Comporterebbe la riscrittura di
tutti i casi d'uso fatti da noi. Voi siete andati a capo per i case d'uso?
Il 19 gen 2016 16:03, "Giovanni Mazzocchin" notifications@github.com ha
scritto:

**Comment by WeissL** [comment]
Riscritti
