### ISSUE TITLE
Aggiungere descrizioni delle relazioni moduli frontend

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#370]
Documento in cui si trova il problema: 
Activity #318 
Specifica Tecnica 

Descrizione del problema: 
Descrivere le relazioni tra i moduli del frontend come chiesto nella correzione

Link task: [https://bugbusters.teamwork.com/tasks/6487160](https://bugbusters.teamwork.com/tasks/6487160)

**Comment by mdipirro** [comment]
@WeissL e questa?
