### ISSUE TITLE
Casi d'uso Editor

### ISSUE THREAD

**Issue by WeissL** [BugBusterSWE/documentation#38]
- "Scenario Principale" al posto di flusso principale
- Terminologie che derviano dal capitolato vanno in inglese (esempio, non "proprietario" ma "owner")
- La tabulazione che sia corrispondente agli altri casi d'uso: ogni punto va su una nuova riga, non tutti di fila
- Che le Pre si riferiscano a qualcosa dell'applicazione e non ad ignoti(es: "sia cllegata a un Index Element" non possiamo usarla come pre perche non vuol dire nulla come frase presa al di fuori del contesto)
- In generale gli scenari spiegano cosa può fare un attore, non vanno bene frasi senza verbo

**Comment by Polpetta** [comment]
@WeissL 
- Riporto come da ultimo testo del verbale:

```
- Discutere impaginazione casi d’uso
Viene approvata l’attuale strutturazione dei casi d’uso nel documento Analisi dei Requisiti
```

Ove la strutturazione decisa era quello dello script da me creato, che riposta la seguente struttura:

``` bash
if [ -z $IMG_PATH ]
    then
    msg v "No image added"
    else
    msg v "Adding image to UC"

    echo " 

    \begin{figure}[H]
      \begin{center}
        \includegraphics[width=12cm]{res/img/$IMG_PATH}
      \caption{$UC_ID - $UC_NAME}
      \end{center} 
    \end{figure}" | tee -a ../RR/AnalisiDeiRequisiti/res/sections/$TEX_PATH
    fi

    echo "
    %Tabella 
    \begin{center}
      \bgroup
      \def\arraystretch{1.8}     
      \begin{longtable}{  p{3.5cm} | p{8cm} } 

        \hline
        \multicolumn{2}{ | c | }{ \cellcolor[gray]{0.9} \textbf{$UC_ID - $UC_NAME}} \\\\ 
        \hline

        \textbf{Attori Primari} & $ACTOR \\\\ 
        \textbf{Scopo e Descrizione} & $PURPOSE \\\\ 

        \textbf{Precondizioni}  & $PRE \\\\ 

        \textbf{Postcondizioni} & $POST \\\\ 
        \textbf{Flusso Principale} & $FLUX \\\\
        \textbf{Estensioni} & $EXTENSION \\\\
        \textbf{Inclusioni} & $INCLUSION
      \end{longtable}
      \egroup
    \end{center}" | tee -a ../RR/AnalisiDeiRequisiti/res/sections/$TEX_PATH
```

Dove si evince chiaramente l'uso di Flusso principale e non di "Scenario Principale". Detto questo, sono da considerarsi errati gli altri casi d'uso.
- Ok, necessito di tutti i vocaboli da sostiuire (serve che siano una lista di vocaboli _precisi_ o non sostituiro' nulla in quanto non so quali termini cambiare)
- Rispondo sia per questa issue che per #37: come e' strutturato il codice Latex ora, questa cosa non e' possibile. Si dovrebbe fare un overloading della funzione `table` in latex per eliminare tutti gli spazi che si verrebbero a creare. Un workaround e' usando `\newline` al posto dell'elenco puntato: questo genera meno spazi ma rimane comunque un layout brutto e tendere a rompere l'aspetto delle tabelle. Nota che devo ancora apprendere come ridefinire funzioni che hanno questo tipo di complessita'.
- Rispondendo al tuo specifico esempio: Index Element e' nel contesto dell'Editor. Ovvio che i casi d'uso estraniati dal loro contesto non siano comprensibili. Se necessiti di cio', allora la voce va inserita nel Glossario. Coordinati con @korut94 per la creazioni di queste voci.
- Come chiesto due punti fa, dammi una lista di tutti i casi d'uso (codice dell'UC o righe del codice latex) che non vanno bene e su cui c'e' da rielaborare. Posta in questa situazione, un non verificatore non si puo' occupare di rileggere l'intero documento in quanto non e' nelle sue mansioni, ma nelle mansioni del verificatore stesso, che deve occuparsi di segnalare gli errori in modo preciso: altrimenti l'atto di verifica va a riversarsi su colui che ha steso la parte del documento e quindi l'azione di verifica sarebbe vana (un autore del file non puo' verificare lo stesso file)

**Comment by korut94** [comment]
Possiamo chiudere l'issue?

**Comment by Polpetta** [comment]
Si, penso che ora come ora in ogni caso sia da chiudere.
