### ISSUE TITLE
Estensione caso d'uso UC-U9 

### ISSUE THREAD

**Issue by WeissL** [BugBusterSWE/documentation#39]
l'estensione 2 e`marcata con il TODO.
E` da verificare se si necessita di aggiunta o se se bisogna eliminarla.
Era il punto in cui si parlava del caso dell-eliminazione del profilo da parte di un owner

**Comment by WeissL** [comment]
Rivedere anche il punto 9.3 collegato

**Comment by Polpetta** [comment]
@WeissL issue incompleta:
- Manca milestone
- Manca estimate
- Manca assegnatario

Da correggere

**Comment by WeissL** [comment]
Cassata per release
