### ISSUE TITLE
Controllo casi d'uso editor

### ISSUE THREAD

**Issue by korut94** [BugBusterSWE/documentation#4]
Da controllare:
- [x] Identificatori casi d'uso
- [x] Consistenza nomi documentazione scritta e diagrammi
- [x] Correttezza dei diagrammi
- [x] Sufficienza dell'analisi

**Comment by Polpetta** [comment]
è ancora valida questa issue @korut94?

**Comment by korut94** [comment]
E' forse più corretta come guida generica per i Verificatori.

**Comment by Polpetta** [comment]
Come guida generica? Ok, allora va cambiata la milestone penso.
