### ISSUE TITLE
Togliere regola Lint implicit-any

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#414]
_Documento in cui si trova il problema_: 
Activity #399 
Norme di progetto

_Descrizione del problema_: 
Eliminare la regola sull'implicit-any

Link task: [https://bugbusters.teamwork.com/tasks/6649405](https://bugbusters.teamwork.com/tasks/6649405)

**Comment by mdipirro** [comment]
@Polpetta possiamo chiudere per quanto detto stamattina?

**Comment by Polpetta** [comment]
Si.
