### ISSUE TITLE
[REQUISITI] - Urgente

### ISSUE THREAD

**Issue by EmanueleC** [BugBusterSWE/documentation#45]
Io ho fatto una lista con tutti i requisiti derivati dai casi d'uso dell'utente. A che punto sono gli altri? 
Occorre che una persona che non li abbia scritti li verifichi prima che siano situati in tabella.
Va valutato anche l'ordine (visto che nelle Norme di Progetto è specificato che la lista di requisiti va organizzata per importanza).

**Comment by Polpetta** [comment]
@EmanueleC per avere piu' risonanza manda il link della issue anche sul gruppo!! :blush:

**Comment by korut94** [comment]
Ma Emanuele ti sei unito con i miei?

**Comment by EmanueleC** [comment]
Ora sì

**Comment by Polpetta** [comment]
@EmanueleC a che stato e' questa issue? E' chiudibile?
