### ISSUE TITLE
Firme

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#46]
Che fare con le firme?

**Comment by WeissL** [comment]
Consegna a mano come ha detto il Professore?

**Comment by Polpetta** [comment]
@mdipirro È più facile consegnare tutto online, ma se vogliamo fare a mano per me non ci sono problemi.

**Comment by mdipirro** [comment]
A me va bene cosegnarle online

**Comment by drigoni** [comment]
Mandate e a me e le inserisco nel Pdp in velocità.  Se poi servono per altri documenti inserisco la tabella anche li
