### ISSUE TITLE
Aggiornare stato test - 2

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#463]
_Documento in cui si trova il problema_:
Activity #443
Piano di Qualifica

_Descrizione del problema_:
Aggiornare lo stato dei test dal numero TU-30 fino al TU-58 del file in posizione `official/PianoDiQualifica/res/sections/unitTests/backend.tex`. 
In caso non ci siano test da aggiornare segnarlo nel task e chiuderlo senza pull request

Link task: [https://bugbusters.teamwork.com/tasks/6736129](https://bugbusters.teamwork.com/tasks/6736129)

**Comment by WeissL** [comment]
Test non ancora implementati
