### ISSUE TITLE
Descrizione generale AR [urgente]

### ISSUE THREAD

**Issue by EmanueleC** [BugBusterSWE/documentation#47]
Ho iniziato a scrivere la descrizione dell AR. Qualcuno riesce a completare i punti rimanenti?

**Comment by Polpetta** [comment]
@BugBusterSWE/adr-editor @BugBusterSWE/adr-superadmin @BugBusterSWE/adr-user 

Qualcuno se ne occupa?

**Comment by EmanueleC** [comment]
Se ne occupa Luca

**Comment by EmanueleC** [comment]
@WeissL hai scritto i punti rimanenti dell'introduzione?

**Comment by WeissL** [comment]
Sto finendo, appena aggiungo mandò un messaggio sul gruppo

**Comment by Polpetta** [comment]
@WeissL questa issue e' stata completata?

**Comment by WeissL** [comment]
Fatta e corretta
