### ISSUE TITLE
Slide con logo GitBook e/o formati esportabili

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#481]
Fare slide per la spiegazione dei vantaggi di GitBook
Activity #473

Link task: [https://bugbusters.teamwork.com/tasks/6791941](https://bugbusters.teamwork.com/tasks/6791941)

**Comment by korut94** [comment]
@mdipirro per te faccio due slide: una con i vantaggi di gitbooks e un'altra con elencati i formati esportabili? O solo una con logo gitbooks e formati esportabili?

**Comment by mdipirro** [comment]
come pensi sia meglio.. anche una unica semplicemente con i loghi e poi ci si parla sopra.. sennò sono troppo scritte
