### ISSUE TITLE
Slide organizzazione repository codice

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#482]
Slide organizzazione repository codice 
Activity #473

Link task: [https://bugbusters.teamwork.com/tasks/6792120](https://bugbusters.teamwork.com/tasks/6792120)

**Comment by Polpetta** [comment]
@drigoni questo l'avevi fatto te giusto? :blush:

**Comment by drigoni** [comment]
Si, ho già creato la struttura. Me la assegno e chiudo

**Comment by Polpetta** [comment]
Ok
