### ISSUE TITLE
Errori trovati in AR

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#49]
Non voglio fare modifiche al documento AR perché temo di fare casini. Quindi elenco qua gli errori che trovo. Chi li ha fatti se ne occupi (alcuni includono anche il glossario).

<h1>Generale</h1>
- [x] Manca il numero totale delle pagine
- [x] Manca indice
- [x] Manca elenco delle figure
- [ ] Manca tabella versioni
- [x] Manca descrizione
- [ ] Tabella redattori ecc... è errata
- [ ] MaaP è un'applicazione web?? paragrafo 1.2
- [ ] "Glossario v2.0.0" e "contenente" sono attaccati, paragrafo 1.3
- [ ] Owner impersona altri utenti?? non era il super-Admin a doverlo fare? paragrafo 2.3
- [ ] Ci deve andare la sezione su come rinominiamo i casi d'uso? non c'è...

<h1>Introduzione</h1>
- [x] "funzionalità che dovrà disporre"
- [x] MaaP e non Maap
- [x] swebok non swebook
- [x] mancano voci di glossario su MaaS e MaaP.
- [x] gli acronimi MaaS e MaaP non sono descritti la prima volta in cui compaiono

<h1>Descrizione generale</h1>

 glossario e acronimo per SaaS
- [x] "Ciascuna funzione associata a un ruolo è può essere"
- [x] "La seguente elencazione"
- [ ] Metterei il titolo SuperAdmin nella pagina seguente
- [x] Manca la sezione Vincoli
- [x] Manca la sezione Contesto d’utilizzo
- [x] Manca la sezione Funzione di Prodotto

<h1>Utente non autenticato</h1>
- [x] "durante procedura", meglio "durante la procedura" in 1.1 e 1.2
- [x] uniformare 1.3 a 1.1 e 1.2 o viceversa (1.3 ha lo scenario, gli altri due no)
- [x] 3, l'invito è ricevuto da Company Owner o da Company e vbasta? Uniformare
- [ ] 4, perché c'è "attore" e non "utente non autenticato" in POST?
- [ ] 5, farlo iniziare in una nuova pagina
- [ ] 7, farlo iniziare in una nuova pagina

<h1>Utente autenticato</h1>
- [x] casi d'uso è senza G
- [ ] Far partire la sezione in una nuova pagina
- [x] Dashboard è in corsivo ma non ha la G, oppure scritto senza corsivo (dappertutto)
- [x] 8 in Estensioni c'è "proceduro"
- [ ] 9 sarebbe meglio avere solo linee rette nelle immagini
- [ ] 9 in "Scopo e Descrizione" sembra ci siano due spazi dopo i :
- [x] 9.1 in POST "indirizzo email" al posto di "mail"
- [x] 9.1.1 "Nessuno" in Scenario Principale. Toglierlo perché non c'è negli altri UC senza scenario
- [ ] 9.2 nell'immagine sarebbe più bello avere una linea verticale e non obliqua per la prima PRE
- [ ] 9.4 in una nuova pagina
- [x] 9.4 mancano le G nei termini da glossario
- [ ] 9.4 in POST "Utente autenticato", non "attore"
- [x] 9.4 in POST "utenti registrati della Company" mi lascia dubbioso, chiarire magari con "utenti collegati alla Company"
- [ ] Manca UC10
- [ ] 11 Owner è in inglese, ma allora dovrebbero esserlo anche Ospite e Membro
- [x] 11 G su Owner
- [ ] A volte è scritto "Utente Autenticato", altre "Utente autenticato" (A oppure a), uniformare
- [ ] 11.1, 11.2, 11.3, 11.4 in POST meglio "specifica DSL" che "DSL"
- [x] 13 (dappertutto), "Admin", non "Amministratore"
- [x] 13 in Scopo: meglio "oppure" rispetto ad "e" dopo "accedere all'editor"
- [ ] 13 in "Scenario Principale" il punto 3. ha un tab
- [ ] 13.1 in PRE "specifica DSL" e non "DSL" e errore di battitura in "selezionata"
- [ ] 13.5 nuova pagina
- [ ] si passa da 13.5 a 13.6.2
- [ ] 13.6.2 in Scopo "procedura" non è marcata come termine di glossario
- [ ] 13.6.2 in PRE "sistema" è nel glossario?
- [ ] 14 è duplicato di 12
- [x] 16 (e figli) nell'immagine cell, document e collection a volte hanno l'iniziale maiuscola, altre no
- [x] 16 "element" è nel glossario? e "cell", "document" e "collection"?
- [ ] 16.2 perché in una nuova pagina?
- [x] 16.5 "query" è nel glossario?
- [ ] UC-U16.5 Ordinare i valori in una cell? non dovrebbe essere possibile farlo dalla collection?
- [ ] 16.5.2 nuova pagina
- [ ] 16.6 meglio se l'estensione è nella stessa riga
- [x] 16.6 in "scenario principale" manca un ritorno a capo prima di 2.
- [ ] 16.6.4 (e seguenti) "json" e "csv" non hanno la G
- [ ] 16.6.5 "mail" o "email"?
- [ ] 16.7 nell'immagine perché l'estensione è in inglese?
- [x] 16.7 in "Estensioni" c'è ".json" e ".csv" non marcati e in disaccordo con 16.6.4 (non c'è il .)
- [ ] 16.7.3 nuova pagina
- [x] 16.7.3 "mail" o "email"?
- [ ] 16.7.4 in POST c'è uno spazio prima di .
- [ ] 17 nuova pagina

<h1>Editor</h1>
- [ ] ma siamo sicuri che l'ospite possa modificare i DSL??
- [x] le immagini hanno il logo di Astah
- [ ] "il sistema dispone" è bruttissimo
- [x] casi d'uso è senza G
- [ ] 0 siamo sicuri di quella mega immagine ?
- [ ] 0 (e successivi) mancano le G sui termini da glossario
- [x] 0 in "Scopo" "puòsvolgere"
- [x] 0 in PRE meglio "prepara" o "apre" di "dispone"
- [x] 0 in POST manca il . alla fine
- [x] 0 in "Scenario principale" non viene mostrato l'elenco (tutto di fila)
- [x] 2 perché si parte da 2.0.ecc? Negli alrti si parte da .1
- [x] "Editor" o "editor", uniformare
- [ ] 2 perché si va a capo tra "Scenario" e "principale"?
- [x] 2 in "scenario principale" è tutto di fila
- [x] 2.0.1 in "Attori primari" "Ospiete"
- [x] 2.0.3 in "Attori primari" "Ospiete"
- [ ] "DSL Dependent Element" non è nel glossario?
- [x] 2.0.3 in PRE "ha a seleziona"
- [ ] 2.0.5 "Function Element" non è nel glossario?
- [x] 2.0.6 in "scopo" "decide di poter avere accesso", in che senso?
- [ ] 2.1 manca uno spazio in unCollection nell'immagine
- [ ] 2.1 "Collection Element" non è nel glossario?
- [x] 2.1 in "Scenario" è tutto su una riga
- [ ] 2.1.1 "Index Element" non è nel glossario (nei seguenti controllare termini specifici)
- [x] 2.1.1 mancano tutti i . alla fine delle frasi
- [x] 2.2 in "Scenario" è tutto su una riga
- [x] 2.2.3 "Function Element" a volte è in corsivo, altre no
- [x] 2.3 in "Scenario" è tutto su una riga
- [x] 2.6 in "scopo" "manipulare"
- [x] 2.6 mancano i . alla fine delle frasi
- [x] 2.6 in "scanrio" è tutto su una riga
- [x] 2.6.1 manca . alla fine di PRE
- [x] 2.6.2 in POST "è stata manipolata ... un attributo Row", sistemare
- [x] 2.6.3 in "scopo" "associazione" è "associazione per riferimento"? Se si, uniformare e marcare con G
- [ ] 2.6.4 nuova pagina
- [ ] "da la possibilità" dovrebbe essere "dà la possibilità" credo
- [x] 2.7 in "scenario" "Lùtente" ed è tutto su una riga
- [x] 2.7.1 le PRE sono uno stato del sistema non una cosa che dee fare l'utente
- [x] 2.8 in "scenario" è tutto su una riga
- [x] 2.8.1 l'elenco dei tipi di dato dovrebbe essere, appunto, un elenco
- [ ] 2.9 in immagine "DashRow"?
- [x] 2.9 in "scenario" è tutto su una riga
- [x] 2.9.1 in PRE si parte con la lettera minuscola
- [x] 2.9.2 in "scopo" manca il .
- [ ] 2.10 stesso problema dell'immagine di 2.9
- [x] 2.10 "dashrow element" o "dashboard element"? sono due cose diverse? sono nel glossario?
- [x] 2.10 in "scenario" è tutto su una riga
- [x] 2.11 in "scenario" è tutto su una riga
- [x] 2.11.2 in "scopo" manca il .
- [ ] 3 nell'immagine "extension point" non è mai stato messo fino ad ora
- [x] 3.1 in "scopo" "affinché", non "affinchè"
- [ ] 3.1 in POST "ha preso in carico" o ha salvato?
- [x] 3.3 in "scopo" si parte con la lettera minuscola
- [x] 3.3 mancano tutti i . a fine frase
- [x] 3.3 in POST "memorizzato al sistema"
- [x] 3.4 mancano gli attori
- [x] 3.4 mancano i . a fine frase

<h1>Super admin</h1>
- [ ] manca res/img/UCSuperadmin/UC-S1.png
- [ ] manca res/img/UCSuperadmin/UC-S2.png
- [ ] manca res/img/UCSuperadmin/UC-S2.0.png
- [ ] manca res/img/UCSuperadmin/UC-S2.1.png
- [ ] manca res/img/UCSuperadmin/UC-S2.2.png
- [ ] manca res/img/UCSuperadmin/UC-S2.3.png
- [ ] manca res/img/UCSuperadmin/UC-S2.4.png
- [ ] manca res/img/UCSuperadmin/UC-S3.png
- [ ] nella immagini degli altri casi d'uso le estensioni hanno un commento con la PRE
- [x] Super-Admin ha volte è marcato a volte no
- [ ] controllare i tab negli elenchi
- [ ] Attore al posto di super admin (lo scrivo anche se è voluto, per conferma)
- [x] 1 in "scenario" al punto 3 manca .
- [x] 1 in "estensioni" il punto 1 inizia con la lettera minuscola
- [x] 2.0 si cominciano le frasi solo con lettere minuscole
- [x] 2.1 si cominciano le frasi solo con lettere minuscole
- [ ] 2.1 in POST "sistema" va nel glossario?
- [x] 2.2 si cominciano le frasi solo con lettere minuscole
- [x] 2.2 in PRE si finisce la frase con ;
- [x] 2.3 si cominciano le frasi solo con lettere minuscole
- [x] 2.4 si cominciano le frasi solo con lettere minuscole
- [x] 3 in "scopo" "poterne vedere" è brutto, meglio "vederne"
- [x] 3 si cominciano le frasi solo con lettere minuscole
- [x] 3.0 si cominciano le frasi solo con lettere minuscole

<h1>Requisiti</h1>
- [ ] "funzionali", "prestazionali", "qualità", "requisito" vanno nel glossario? (qualità si)
- [ ] R1O0 SaaS va nel glossario?
- [ ] R1O2.1 database va nel glossario?
- [x] R1O2.2, meglio "indirizzo email" che "mail"
- [x] R1O2.3.3 aggiungere UC-U9.4 (rimozione compagnia). Inoltre la scelta di un altro Owner non è stata specificata da nessuna parte
- [x] R1O3.2, 3.3, 3.4 >= non mi sembra adatto, meglio "superiore a "
- [x] R1O4.2.4 Document va nel glossario
- [x] R1O7.3 Super-Admin va nel glossario
- [x] R1D11 "scaricare nella Terminale"
- [x] requisiti di qualità hanno X nella numerazione
- [x] R3OX "Nomre di progetto v"  -> non è stato usato il comando \NormeDiProgetto
- [x] requisiti di vincolo hanno numerazione sbagliata
- [x] "heroku" va nel glossario
- [ ] 8.4 e 8.5 ???

**Comment by Cyofanni** [comment]
potresti dire in che file si trovano se hai letto i sorgenti?

**Comment by mdipirro** [comment]
Sto leggendo il pdf, ma i titoli indicano la sezione. Marcate le cose che sistemate.

**Comment by EmanueleC** [comment]
@Cyofanni spunta gli errori che hai risolto

**Comment by Polpetta** [comment]
@BugBusterSWE/verificatori Intervenite a dare una mano a questa issue :sweat_smile:

**Comment by Polpetta** [comment]
@mdipirro Cosa intendi per elenco delle figure? Gli steakholders se l'erano fatto a mano...a me sembra un po' una pazzia sinceramente.

**Comment by mdipirro** [comment]
ok semmai lo faremo alla prossima

**Comment by Polpetta** [comment]
@mdipirro Di questa issue che ne facciamo? L'hai spezzettata in altre sottoissue? La teniamo o la rendiamo invalida e la chiudiamo?
