### ISSUE TITLE
Aggiungere automazione APIDoc

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#497]
_Documento in cui si trova il problema_: 
Norme di Progetto 
Activity #494 

_Descrizione del problema_:
Aggiungere automazione APIDoc

Link task: [https://bugbusters.teamwork.com/tasks/6938623](https://bugbusters.teamwork.com/tasks/6938623)

**Comment by mdipirro** [comment]
Collegata a #496
