### ISSUE TITLE
Aggiungere automazioni mancanti

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#500]
_Documento in cui si trova il problema_: 
Norme di Progetto 
Activity #494 

_Descrizione del problema_:
Aggiungere descrizioni delle automazioni mancanti. In caso di problemi chiedere a @polpetta.

Link task: [https://bugbusters.teamwork.com/tasks/6938626](https://bugbusters.teamwork.com/tasks/6938626)

**Comment by Cyofanni** [comment]
@mdipirro io inserirei le automazioni mancanti nella revisione della profondità dei contenuti.
Posso chiudere?

**Comment by mdipirro** [comment]
in che senso?

**Comment by mdipirro** [comment]
collego le due issue così chi verifica sa che ci sono entrambe le cose

issue #499
