### ISSUE TITLE
Errori trovati nel Glossario

### ISSUE THREAD

**Issue by EmanueleC** [BugBusterSWE/documentation#51]
Sto rivedendo i documenti che non sono riuscito a leggere prima della consegna.
Faccio una lista di cose da sistemare ma suggerisco di aspettare il responso di Tullio prima di modificare i documenti. La lista serve solo come promemoria.

<h2> Generale </h2>

- [x] Alcune lettere cominciano in maiuscolo, altre in minuscolo, alcuni termini sono messi in corsivo a volte e altre no.
- [x] Negli acronimi a volte viene riportata a fianco la sigla es. (SDLC), la maggior parte delle volte NO

<h2> In "versioni del documento" </h2>
- [x] Versione 1.0.4. accento su A di Analisi, va tolto

<h2> Voci del glossario </h2>

- [x] Action Element: "edito" (manca r finale), rivedere definizione
- [x] Cammino critico: "attività-progetto" (?)
- [x] Classificazione a fasi: "classifcazione"
- [x] Codice sorgente: in una frase vengono ripetute 4 volte parole derivate da programma
- [x] Collection: collezzione NO doppia z. Inoltre quelli nella lista non sono concetti, ma contenuti.
- [x] Configuration: rivedere definizione 1
- [x] Csv: "nell-esportazione"
- [x] Disciplinato, Incremento, Iterazione, Riuso, Prototipo: plural alla fine (?)
- [x] Mancano le voci "index page" e "show page" nel glossario
- [x] Plan Do Check Act: manca plan estesto
- [x] Processo Organizzativi, Processo Primari: cambiare processo in processi
- [x] Prototipo: rivedere la seconda frase della definizione
- [x] Riuso: "consapevolee"
- [x] Sistematico: rivedere definizione
- [x] SPICE: in una frase è ripetuta tre volte la parola processi (rivedere)
- [x] Manca la voce "Show" (marcata con G nei casi d'uso dell'editor)

**Comment by WeissL** [comment]
Manca la voce "processo di sviluppo".

**Comment by WeissL** [comment]
Aggiungere voci 
"review": "Revisioni informaili"
"audit": "Revisioni formali"
