### ISSUE TITLE
Inserire misurazioni frontend

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#513]
_Documento in cui si trova il problema_: 
Piano di Qualifica 
Activity #511

_Descrizione del problema_:
Inserire misurazioni frontend

Link task: [https://bugbusters.teamwork.com/tasks/6938644](https://bugbusters.teamwork.com/tasks/6938644)

**Comment by mdipirro** [comment]
Collegato a #512
