### ISSUE TITLE
Aggiornare sezione test con test eseguiti

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#514]
_Documento in cui si trova il problema_: 
Piano di Qualifica 
Activity #511

_Descrizione del problema_:
Aggiornare sezione test con test eseguiti

Link task: [https://bugbusters.teamwork.com/tasks/6938647](https://bugbusters.teamwork.com/tasks/6938647)

**Comment by Polpetta** [comment]
Cambiato assegnatario del task in @Cyofanni
