### ISSUE TITLE
Aggiungere copertura test

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#528]
_Documento in cui si trova il problema_: 
Piano di Qualifica 
Activity #511 

_Descrizione del problema_: 
Inserire misurazioni sulla copertura dei test

Link task: [https://bugbusters.teamwork.com/tasks/6941751](https://bugbusters.teamwork.com/tasks/6941751)

**Comment by Polpetta** [comment]
Cambiato assegnatario in @Cyofanni
