### ISSUE TITLE
Errori trovati nelle Norme di Progetto

### ISSUE THREAD

**Issue by drigoni** [BugBusterSWE/documentation#54]
- [x] "Maap" con la p in minuscolo, paragrafo 1.2
- [x] "Maap" in minuscolo e non collegata al glossario, paragrafo 1.2
- [x] "software" in corsivo ma non collegata al glossario, paragrafo 2.1
- [x] Voci non collegate con il glossario, alcune volte in corsivo ed altre no, paragrafo 2.1.2
- [x] "(??)" presente in paragrafo 4.1.5
- [x] Voci poste a fine pagina e non nel glossario. Errore? Paragrafo 4.1.5

**Comment by WeissL** [comment]
@drigoni : per il terzo punto ho tolto anche il corsivo. Secondo me non ha senso specificare software nel glossario

**Comment by Polpetta** [comment]
Bisognerebbe sentire il responsabile che dice!! ☺
Il 29 feb 2016 10:24, "WeissL" notifications@github.com ha scritto:

**Comment by WeissL** [comment]
@EmanueleC scelgo te! l'hai fatta tu la parte dei processi organizzativi giusto? mi potresti dire cosa riguarda la voce in cui ci sono i "??" citati nel punto? c'è un riferimento a "presentazione" ma non riesco a capire a quale presentazione ti riferisci

**Comment by mdipirro** [comment]
si direi che software lo possiamo dare per conosciuto

**Comment by EmanueleC** [comment]
@WeissL Non ho scritto io quella parte. Mi pare sia stato @Cyofanni. Probabilmente voleva mettere un riferimento all'elenco puntato subito dopo quello numerato (sezione 4.1.5). Per fare questo si deve mettere \ref{itm:presentazione} (mancava itm su ref)

**Comment by Cyofanni** [comment]
la parte sui Processi Organizzativi l'ha fatta @Polpetta

**Comment by EmanueleC** [comment]
Ok, mi scuso :sweat_smile:

**Comment by Polpetta** [comment]
Eccomi. La riga incriminata e' questa giusto?

``` tex
\item Management preparation: il Responsabile si assicura che tutti i membri del gruppo possano partecipare e l'ambiente di lavoro rispetti i vincoli imposti o suggeriti dal committente. A tal fine è stata elaborata una lista di indicazioni (\ref{presentazione});
```

Il `\ref{presentazione}` voleva riferirsi a questo punto del documento

``` tex
\label{itm:presentazione}
Le indicazioni su come costruire una presentazione sono le seguenti:
```

che pero' essendo stata cambiata la label (non so chi sia stato) il compilatore non ha trovato i riferimenti, e ha sostituito il tutto con due punti di domanda. Il `ref` deve puntare a una `label` valida, o si hanno queste "feature"

**Comment by WeissL** [comment]
quindi come lo correggo?

**Comment by Polpetta** [comment]
Come vuoi, basta che la label e il ref abbiano lo stesso identificativo.
Puoi controllare da locale se ciò è avvenuto (quindi se non ci sono punti
di domanda) dando il comando make -B official (ti compila solo i documenti
in official senza compilare tutto il repo)
Il 01 mar 2016 20:39, "WeissL" notifications@github.com ha scritto:
