### ISSUE TITLE
Errori trovati nel Piano di Qualifica

### ISSUE THREAD

**Issue by drigoni** [BugBusterSWE/documentation#55]
- [x] 'company' necessita il pedice essendo in inglese? paragrafo 1.1
- [x] Le parole 'Glossario v2.0.0' e 'sono', sono attaccate, paragrafo 1.3
- [x] E' corretta la parola 'Tool's con pedice in tool? paragrafo 2 - 2.6.1
- [x] Parole poste a fine pagina, paragrafo 2.1.2, pag. 11
- [x] PCDA?? non PDCA?? paragrafo 2.1.1
- [x] Piano di progetto in corsivo? paragrafo 2.3
- [x]  "Verificatori" ? sezione A.1.1 
- [x] Scala SPICE al contrario e parte da 1 (invece che da 0)
- [x] "piossono" 2.6.2/Numero di cambiamenti apportati

**Comment by WeissL** [comment]
@mdipirro paragrafo 2.3: il richiamo a piano di progetto deve essere fatto con \PianoDiProgetto?

**Comment by Polpetta** [comment]
Bisognerebbe chiedere a @drigoni che cosa intendesse per il corsivo 😅
Il 29 feb 2016 09:27, "WeissL" notifications@github.com ha scritto:

**Comment by mdipirro** [comment]
@WeissL si
