### ISSUE TITLE
Inserire motivazioni ritardo

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#556]
_Documento in cui si trova il problema_: 
Piano di Progetto 
Activity #507 

_Descrizione del problema_: 
Approfondire analisi dei rischi spiegando le motivazioni del ritardo

Link task: [https://bugbusters.teamwork.com/tasks/7200710](https://bugbusters.teamwork.com/tasks/7200710)

**Comment by Cyofanni** [comment]
@mdipirro in quale sezione del PdP metto le motivazioni del ritardo?
