### ISSUE TITLE
MIglioramento AdR - 1

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#63]
_Documento in cui si trova il problema_:
Analisi dei requisiti

_Descrizione del problema_:
Vedere pdf con esito RR

_Punti da svolgere per risolvere il problema_:
- [x] Rivedere casi d'uso Super Admin
- [x] Correggere punti indicati nel documento

**Comment by Polpetta** [comment]
Chiudo in quanto confluita con #64
