### ISSUE TITLE
Miglioramento AdR - 2

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#64]
_Documento in cui si trova il problema_:
Analisi dei Requisiti

_Descrizione del problema_:
Vedere pdf esito RR

_Punti da svolgere per risolvere il problema_:
- [x] Specificare meglio i requisiti
- [x] Correggere punti indicati nel documento

**Comment by EmanueleC** [comment]
Lista dei commenti della RR (l'ho scritta così vedo cosa manca da sistemare):
- [x] Sarebbe utile un diagramma dei casi d’uso che riassuma le relazioni che sussistono fra i vari attori del sistema. 
- [x] UC0: il primo attore che si incontra non ha alcun riferimento ai ruoli definiti in precedenza. 
  È corretto dal punto di vista della sicurezza che un utente non ancora identificato nell’applicazione possa creare contenuti (Company)? 
- [x] UC-U3: il processo di registrazione non è chiaro. È corretto che l’utente debba inserire unicamente la password e debba farlo una volta sola? 
- [x] UC-U4.1 e UC-U4.2 e altri casi d’uso successivi non possiedono lo scenario principale. 
- [x] Dare un nome parlante ai paragrafi, in modo che la lettura del documento risulti più semplice. 
- [x] UC-U6: chi invia il codice segreto all’utente? L’invio non dovrebbe essere effettuato durante la procedura di recupero password? 
- [x] UC-U9: essendo l’email dell’utente l’elemento identificativo dello stesso nel sistema non dovrebbe poter essere modificata. 
- [x] UC-U9.1 può considerarsi ad un livello di dettaglio già sufficiente e non è necessario andare in ulteriore dettaglio con i diagrammi dei casi d’uso ad esso associati. 
- [x] UC-U9.4: va rivista la sua collocazione all’interno del documento. Inoltre, essendo una funzione 
  potenzialmente distruttiva, per essa va predisposto un workflow più articolato e ragionato. 
- [x] UC-U11: inserire solamente gli attori che partecipano effettivamente ad almeno un caso d’uso nel diagramma. 
- [x] Il termine DSL viene utilizzato in modo non opportuno. Probabilmente il fornitore si riferisce a una “istruzione” definita in un DSL (Domain Specific Language). I suoi sotto-casi d’uso devono essere maggiormente descritti perché non è chiaro quali siano le operazioni che si stanno descrivendo. 
- [x] UC-U13: rivedere le precondizioni. 
- [x] UC-U16.1 e i casi d’uso derivati cosa condividono? Pre-condizioni? Post-condizioni? Nel caso in cui non ci sia alcun punto di contatto, allora la condizione non è corretta. 
- [x] Rivedere la relazione fra UC-U16.7.4 e la sua estensione. 
- [x] R1O 0: eliminare il requisito perché non misurabile. 
- [x] R1O 1: suddividere in sotto-requisiti. 
- [x] R1O 2.1: perché questo e altri requisiti sono derivati da R1O 2? Ci sono vincoli sulle password? 
- [x] R1O 3 e derivati: scendere maggiormente nel dettaglio. 
- [x] Non sono riportati i requisiti minimi (HW e SW) per eseguire l’applicazione.
