### ISSUE TITLE
Miglioramento NdP

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#65]
_Documento in cui si trova il problema_:
Norme di Progetto

_Descrizione del problema_:
Vedere pdf esito RR

_Punti da svolgere per risolvere il problema_:
- [x] Correggere punti indicati nel documento

**Comment by drigoni** [comment]
Riporto cose da fare: 

> La struttura del documento riflette, in linea di principio, l'approccio discusso
> in aula. Le attività svolte intorno alla preparazione dell'offerta tecnicaeconomica
> per la partecipazione al progetto sono parte del processo di
> fornitura, appartenente ai processi primari. I processi si strutturano
> internamente in attività (che quindi diventano il terzo livello gerarchico della
> struttura del documento) e non in prodotti (documenti o altro), come invece
> implica la vostra struttura. §3.1: è opportuno che alle attività venga associate
> un indice numerico, in modo che esse possano essere più agilmente e
> precisamente riferite. In generale, i contenuti del documento si fermano a un
> livello di dettaglio insufficiente a normare con precisione le attività di
> progetto, e non si raccordano con precise scelte di infrastrutture tecniche di
> automazione e supporto. Documento da rivedere e integrare.

**Comment by drigoni** [comment]
- [ ] OrganizativeProcess.tex -> Riga 3: C'è un commento che si riferisce a cose che mancano? 
- [ ] OrganizativeProcess.tex -> Riga 111: Come sopra è presente un commento che mette dubbi.
- [ ] PrimaryProcess.text -> Riga 184: E' il caso di inserire il link in latex piuttosto che lasciarlo comentato?
- [ ] PrimaryProcess.text -> Riga 185: E' il caso di inserire il link in latex piuttosto che lasciarlo comentato?

**Comment by Polpetta** [comment]
@drigoni I punti mettili nella pull request, non nel task! :blush:
