### ISSUE TITLE
Miglioramento PdP

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#67]
_Documento in cui si trova il problema_:
Piano di Progetto

_Descrizione del problema_:
Vedere pdf esito RR

_Punti da svolgere per risolvere il problema_:
- [ ] Correggere i punti indicati nel documento

**Comment by drigoni** [comment]
Riporto la valutazione di Tullio:

> §1.6: la scelta di tipo di RP (min o max) deve essere specificata, perché ha
> impatto significativo sulla pianificazione. Apprezzabile l'intento delle attività
> di controllo specificate nell'analisi dei rischi: esse però diventano veramente
> utili solo se descritte con sufficiente precisione di dettaglio e di calendario per
> essere attuate in modo sistematico. L'analisi dei rischi va infatti sempre
> attualizzata alla situazione corrente. §3: non è opportuno associare il nome di
> specifiche attività a fasi temporali di progetto, perché, in generale, più attività
> saranno simultaneamente attive in ogni fase. Questo errore diventa grave nella
> denominazione di §3.5, che sembra suggerire che le attività di verifica siano
> limitate al breve lasso temporale dell'omonima "fase". §4: il preventivo
> economico deve separare chiaramente i costi rendicontabili (le attività svolte
> tra il superamento della RR e il superamento della RR) dall'investimento (che
> include le attività di progetto precedenti all'ingresso in RR, ma non può
> limitarsi a esse). Il titolo di §6 suggerisce contenuti riguardanti il consuntivo
> di periodo, e il preventivo a finire che da esso deriva: ciò non è invece il caso
> nel vostro documento: in generale, l'analisi del consuntivo di periodo serve a
> determinare azioni correttive utili a preservare quanto più possibile la
> pianificazione iniziale. Nel complesso, documento discreto ma da migliorare.

**Comment by Cyofanni** [comment]
- [x] aggiungere scelta RP (min o max)
- [x] precisare attivita' di controllo dei rischi
- [x] attualizzare i rischi  
- [x]  non è opportuno associare il nome di
  specifiche attività a fasi temporali di progetto, perché, in generale, più attività
  saranno simultaneamente attive in ogni fase. Questo errore diventa grave nella
  denominazione di §3.5, che sembra suggerire che le attività di verifica siano
  limitate al breve lasso temporale dell'omonima "fase".
- [x] il preventivo
  economico deve separare chiaramente i costi rendicontabili (le attività svolte
  tra il superamento della RR e il superamento della RP) dall'investimento (che
  include le attività di progetto Il titolo di §6 suggerisce contenuti riguardanti il consuntivo
  di periodo, e il preventivo a finire che da esso deriva: ciò non è invece il caso
  nel vostro documento: in generale, l'analisi del consuntivo di periodo serve a
  determinare azioni correttive utili a preservare quanto più possibile la
  pianificazione iniziale. all'ingresso in RR, ma non può
  limitarsi a esse).
- [x] fase ---> periodo
- [x] Aggiungere \textit sui nomi dei periodi

**Comment by Cyofanni** [comment]
@mdipirro potresti scrivere a tullio per chiedere una spiegazione dettagliata sul checkbox non spuntato?

scrivi questo:
Riporto il seguente punto dall'esito della RR: [il preventivo economico deve separare chiaramente i costi rendicontabili (le attività svolte tra il superamento della RR e il superamento della RP) dall'investimento (che include le attività di progetto Il titolo di §6 suggerisce contenuti riguardanti il consuntivo di periodo, e il preventivo a finire che da esso deriva: ciò non è invece il caso nel vostro documento: in generale, l'analisi del consuntivo di periodo serve a determinare azioni correttive utili a preservare quanto più possibile la pianificazione iniziale. all'ingresso in RR, ma non può limitarsi a esse).]

non ci è chiaro quale dovrebbe essere il contenuto della sezione "Consuntivo e preventivo a finire" . 

Potrebbe spiegarci più dettagliatamente il nostro errore?"

**Comment by Cyofanni** [comment]
copio la risposta di tullio:
"Il consuntivo riporta le spese effettuate durante il periodo di rendicontazione (cioè dalla data di effettivo superamento della RR, fino alla data di redazione del PdP, nella versione corrente).

Il preventivo a finire è invece l'aggiornamento del preventivo iniziale (quello riportato nella documentazione di ingresso alla RR) riferito però solo al periodo di progetto rimanente, quindi complementare a quello di cui sopra, rispetto alla data prevista di fine progetto.
Sia l'uno che l'altro evolvono, il primo ampliandosi e il secondo riducendosi per ampiezza, fino a che esiste solo il consuntivo e il progetto è finito."

**Comment by mdipirro** [comment]
ma quando abbiamo fatto la presentazione non aveva detto che il "preventivo a finire" non esiste?

**Comment by mdipirro** [comment]
no era il consuntivo a finire che non esiste, sono scemo io
