### ISSUE TITLE
Testare Jenkins

### ISSUE THREAD

**Issue by Polpetta** [BugBusterSWE/documentation#80]
_Documento in cui si trova il problema_: Nessuno

_Descrizione del problema_: Testare Jenkins

_Punti da svolgere per risolvere il problema_:
- [x] Qualche push a caso su un branch che verra' cancellato

**Comment by mdipirro** [comment]
Posso chiudere?

**Comment by Polpetta** [comment]
Mmm lascia qui che chiudo io e cancello il branch!:) lo uso per prova con
Jenkins!
Il 30 mar 2016 16:41, "Matteo Di Pirro" notifications@github.com ha
scritto:
