### ISSUE TITLE
Norme per indice decisioni

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/documentation#93]
_Documento in cui si trova il problema_:
Norme di progetto

_Descrizione del problema_:
Mancano le norme sugli indici per tracciare le decisioni

_Punti da svolgere per risolvere il problema_:
- [ ] Aggiungere norme sugli indici per tracciare le decisioni

**Comment by Polpetta** [comment]
Come mai si è duplicato? :D
Il 14 mar 2016 16:11, "Butler Busters" notifications@github.com ha
scritto:

**Comment by mdipirro** [comment]
avevo assegnato due persone

**Comment by korut94** [comment]
Secondo me è stato il bot. In qualche modo si è svegliato tardi.

**Comment by Polpetta** [comment]
Dici che heroku potrebbe fare scherzi del genere?
Il 14 mar 2016 16:23, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
Heroku ci lascia a piedi sicuro. Adesso penso di inviare un messaggio di conferma ad ogni operazione. @mdipirro sei d'accordo?

**Comment by Polpetta** [comment]
Il bot deve girare forzatamente sulla porta 80?:) perché possiamo anche
spostarlo nel server (spazio permettendo), certo che cambiare ancora
sarebbe una rottura!
Il 14 mar 2016 16:42, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
Il bot attende sulla porta 8080 che è quella che OpenShift prende di default. Cambiare ancora non so quanto sia utile, è più importante mettere che il bot invii un messaggio cosi l'amministratore sa che è andato tutto a buon fine.

**Comment by Polpetta** [comment]
Piano. Il bot è su openshift o su heroku? Non mi ricordo più. Nel caso che
sia su openshift ha senso lasciarlo la Perché tanto non va mai in pausa, e
risparmia risorse al server (e soprattutto spazio ahimè)
Il 14 mar 2016 17:00, "Andrea Mantovani" notifications@github.com ha
scritto:
